Repository InjectiveLabs/cosmos-sdk, pull requests merged in 2025-05, with the labels that each got.

#38 fix: make Testnetify func exported and working
  server/start.go
Labels: Stale

#57 fix: missing x/tx/signing patch for EVM support
  x/tx/signing/context.go
Labels: C:x/tx

#58 [CP-379] backport sdk patch
  CHANGELOG.md
  baseapp/abci_utils.go
  baseapp/abci_utils_test.go
  x/tx/internal/testpb/signers.proto
  x/tx/internal/testpb/signers.pulsar.go
Labels: C:x/tx

#59 [CP-390] deposit validator rewards pool restricted for non-staking token
  baseapp/testutil/mock/mocks.go
  tests/integration/distribution/keeper/msg_server_test.go
  x/distribution/keeper/msg_server.go
  x/distribution/testutil/expected_keepers_mocks.go
  x/distribution/types/expected_keepers.go
  x/staking/testutil/expected_keepers_mocks.go
Labels: C:x/staking, C:x/distribution
